package loganalyzer;

import com.opencsv.bean.CsvBindByName;
import com.opencsv.bean.CsvBindByPosition;

public class ModSecurity extends Log {
    /**
     * Generator for a ModSecurity log object.
     * @param version: version of the ModSecurity that generates the log
     * @param transactionId: transactionId as generated by ModSecurity, example: "ZiDghn8pJCj4T7YiUFJH7AAAAEQ"
     * @param attackName: type of attack detected by ModSecurity, example: "REQUEST-930-APPLICATION-ATTACK-LFI"
     * @param attackMsg: attack analysis by ModSecurity, example: "OS File Access Attempt"
     * @param attackData: detailed analysis of the attack, example: "Matched Data: etc/passwd found within ARGS:username: /etc/passwd"
     * @param severity: severity of the request
     */
    public ModSecurity (String version, String timestamp, String transactionId, String remoteAddress,
                        String path, String method, String protocol, int statusCode, String userAgent,
                        String attackName, String attackMsg, String attackData, String severity) {
        super(remoteAddress, timestamp, method, protocol, path, statusCode, userAgent);
        this.version = version;
        this.transactionId = transactionId;
        this.attackName = attackName;
        this.attackMsg = attackMsg;
        this.attackData = attackData;
        this.severity = severity;
    }

    public String getVersion() {
        return version;
    }

    public String getTransactionId() {
        return transactionId;
    }

    public String getAttackName() {
        return attackName;
    }

    public String getAttackMsg() {
        return attackMsg;
    }

    public String getAttackData() {
        return attackData;
    }

    public String getSeverity() {
        return severity;
    }


    @CsvBindByName(column = "attackName", required = true)
    @CsvBindByPosition(position = 7)
    private final String attackName;

    @CsvBindByName(column = "attackMsg", required = true)
    @CsvBindByPosition(position = 8)
    private final String attackMsg;

    @CsvBindByName(column = "attackData", required = true)
    @CsvBindByPosition(position = 9)
    private final String attackData;

    @CsvBindByName(column = "severity", required = true)
    @CsvBindByPosition(position = 10)
    private final String severity;

    @CsvBindByName(column = "transactionId", required = true)
    @CsvBindByPosition(position = 11)
    private final String transactionId;
    @CsvBindByName(column = "version", required = true)
    @CsvBindByPosition(position = 12)
    private final String version;
}
