node {
  stage('SCM') {
    git branch: 'main', credentialsId: 'trungtqthust-ghub', url: 'https://github.com/trungtqthust/cicd-test.git'
  }
  stage('SonarQube Analysis') {
    def scannerHome = tool 'SonarQube Scanner';
    withSonarQubeEnv() {
    sh "${scannerHome}/bin/sonar-scanner -Dsonar.java.binaries=. -Dsonar.projectKey=jenkins-is-not-hard-lmao -Dsonar.login=sqa_31ca1fc99a4ab6d10e1aef538443bbe8350a921b"
    }
  }
}
